name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

# https://github.com/hyperium/tonic/blob/master/.github/workflows/CI.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Rust info
      run: rustc --version
    - name: Install protoc
      uses: taiki-e/install-action@v2
      with:
        tool: protoc@3.20.3
    - name: Build
      run: cargo build --release
    - name: Run tests
      run: cargo test
      